name: Build
on:
  push:
    branches:
      - "*"

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - run: dotnet build MonikDesktopSolution/MonikDesktopSolution.sln
